package com.capcorp.webservice.models

data class SignupModel(
    val __v: Int?,
    val _id: String?,
    val accessToken: String?,
    var localType: String?,
    val alphaCode: String?,
    val badge: String?,
    var googleId: String?,
    var socialLogin: Boolean?,
    var key: String?,
    var socialType: String?,
    var isUserExists: Boolean?,
    val country: String?,
    val countryCode: String?,
    val countryISO: String?,
    val createdDate: Long?,
    val dateFilter: Boolean?,
    val dateOfBirth: String?,
    val defaultLocation: ArrayList<Double>?,
    val deliveryOrders: Boolean?,
    val deviceToken: String?,
    val deviceType: String?,
    val discoveryRadius: Float?,
    val documentUploaded: Boolean?,
    val documents: ArrayList<Document>?,
    val driverTotalNumberOfRating: Float?,
    val driverTotalRating: Float?,
    val editBadge: Boolean?,
    val emailId: String?,
    val employeeCode: String?,
    val endDate: Int?,
    val filterType: String?,
    val firstName: String?,
    val fullName: String?,
    val fullNumber: String?,
    val highestEarningOrders: Boolean?,
    val isAgreementSign: Boolean?,
    val isApproved: Int?,
    val isBlock: Boolean?,
    val isDeactivate: Boolean?,
    val isDeleted: Boolean?,
    val isDriverDeactivate: Boolean?,
    val isEmailVerified: Boolean?,
    val isMute: Boolean?,
    val isSwitched: Boolean?,
    val isVerified: Boolean?,
    val language: Int?,
    val lastName: String?,
    val isStripeConnect: String?,
    val leastEarningOrders: Boolean?,
    val location: List<Double>?,
    val nearestOrders: Boolean?,
    val noDilvery: Boolean?,
    val numericCode: String?,
    val otp: Int?,
    val payment: Float?,
    val paymentFilterOrders: Float?,
    val phoneNo: String?,
    val pickUpOrders: Boolean?,
    val profilePicURL: ProfilePicURL?,
    val reasonForDeactivate: String?,
    val recentOrders: Boolean?,
    val registerType: String?,
    val requestType: String?,
    val rewardFilter: Float?,
    val settingApplied: Boolean?,
    val shopOrders: Boolean?,
    val signupStatus: String?,
    val startDate: Int?,
    val stripeConnectId: String?,
    val totalNumberOfRating: Float?,
    val totalRating: Float?,
    val type: String?,
    val userExists: Boolean?,
    val bio: String?,
    val reviews: ArrayList<ReviewDetails>?,
    val details: Details

)

data class Document(
    val original: String?,
    val thumbnail: String?
)

data class ReviewDetails(
    val _id: String?,
    val createdDate: Long?,
    val description: String?,
    val type: String?,
    val badge: String?,
    val fullName: String?,
    val from: String?,
    val isApproved: Int?,
    val profilePicURL: ProfilePicURL?,
    val totalRating: Float,
    val Id: String
)

data class ProfilePicURL(
    val original: String?,
    val thumbnail: String?
)
