package com.capcorp.webservice.models.orders

import com.capcorp.webservice.models.ItemImage
import com.capcorp.webservice.models.UserId
import com.capcorp.webservice.models.driver.driver_request_pic.ProductImages
import com.capcorp.webservice.models.driver.driver_request_pic.ReceiptImages
import java.io.Serializable

data class OrderListing(
    var _id: String?,
    var orderId: String?,
    var userId: UserId?,
    var receiverInfo: ReceiverInfo?,
    var orderType: String?,
    var isDriverApproved: Int,
    var stripeConnectId: String? = "",
    var totalCheckout: Double? = 0.0,
    var pickUpDate: Long?,
    var pickUpAddress: String?,
    var pickUpLocation: ArrayList<Double>?,
    var payment: Double = 0.0,
    var createdDate: Long?,
    var orderStatus: String?,
    var driverStatus: String?,
    var offers: List<Offer>?,
    var accepted: UserId?,
    var description: String?,
    var dropDownLocation: ArrayList<Double>?,
    var dropDownAddress: String?,
    var pickUpAdditionalNotes: String?,
    var dropDownAdditionalNotes: String?,
    var type: String?,
    var itemImages: List<ItemImage>?,
    var isDismantleNeeded: Boolean?,
    var isElevated: Boolean?,
    var isFragile: Boolean?,
    var groceryItems: ArrayList<GroceryItem>,
    var dimensionArray: List<Dimension>?,
    var parcelBranchId: ParcelBranchId?,
    var outerParcelImagesURL: List<ItemImage>?,
    var innerParcelImagesURL: List<ItemImage>?,
    var shipItemImages: List<ItemImage>?,
    var productImages: List<ProductImages>,
    var receiptImages: List<ReceiptImages>,
    var itemName: String?,
    var itemUrl: String?,
    var itemPrice: String = "0.0",
    var itemQuantity: String = "1",
    var arrivedDate: Long?,
    var arrivedLatLong: ArrayList<Double>?,
    var pickDate: Long?,
    var pickDateLatLong: ArrayList<Double>?,
    var deliveredDate: Long?,
    var deliveredLatLong: ArrayList<Double>?,
    var purchaseMadeDate: Long?,
    var addressGivenDate: Long?,
    var addReceiptDate: Long?,
    var purchaseMadeLatlong: ArrayList<Double>?,
    var confirmationDate: Long?,
    var confirmationLatLong: ArrayList<Double>?,
    var committedDate: Long?,
    var committedLatLong: ArrayList<Double>?,
    var location: ArrayList<Double>,
    var storeName: String?,
    var isOTPSend: Boolean = false,
    var completeDate: Long?,
    var storeDetails: ArrayList<StoreDetail>,
    var orderCode: String,
    var originalPacking: String,
    var deliveryAddress: String,
    var isUserRated: String,
    var isDriverRated: String,
    var driverTotalRating: Int,
    var recommendedReward: String = "0",
    var driverAverageRating: Float,
    var isDriverCancel: String,
    var insurance: Boolean,
    var tax: String = "0",
    var adminFee: Double?,
    var taxInclude: String = "",
    var prevTotalPrice: String = "",
    var shippingCharge: Double,
    var stripeFee: String? = "0.0",
    var h2dFee: String,
    var itemSize: String?,
    var userCardDetails: UserCardDetail?,
    var myOffers: MyOffers?,
    var couponUse: Boolean?,
    var couponKey: String,
    var discount: Double = 0.0,
    var driverCardDetails: UserCardDetail?
) : Serializable
